### ISSUE TITLE
How do you want to initialize polestar?

### ISSUE THREAD

**Issue by domoritz** [uwdata/ipython-vega-lite#2]
I think this will be a function you call, like

```python
import vega
vega.polestar(dataframe)
```

Thoughts?

**Comment by kanitw** [comment]
why vega.polestar?

Kanit "Ham" Wongsuphasawat
Graduate Student
Computer Science & Engineering
University of Washington
http://kanitw.yellowpigz.com

**Comment by domoritz** [comment]
So you can use this with polestar, voyager and vl. 

Even better would be 

```python
import polestar
polestar.explore(dataframe)
```

```python
import voyager
voyager.explore(dataframe)
```

and so on

**Comment by wrobstory** [comment]
Some thoughts, take them or leave them. 

It might be best to converge on a short-ish library/package namespace under which everything can be imported. Given that this is going to target Jupyter, a workflow like the following makes a lot of sense with a name like `jvega` or some such:

`$ pip install jvega`

```python
import jvega as jv

jv.polestar.explore(dataframe)
jv.voyager.explore(dataframe)
```

The vega-lite integration is going to be trickier, as folks will want to be able to specify actual chart types.

**Comment by domoritz** [comment]
I agree with @wrobstory.

For vega-lite, I expect that inially users have to provide  dictionary that we simply convert to a vega-lite spec in JSON.
